version: '3'

services:

  mantisbt:
    image: vimagick/mantisbt:latest
    container_name: mantisbt
    ports:
      - "8989:80"
    links:
      - mysql
    restart: always
    # networks:
      # - mantis

  mysql:
    image: mysql:5.7
    volumes:
      - ./data:/var/lib/mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mantis
      - MYSQL_USER=mantisbt
      - MYSQL_PASSWORD=mantisbt
    restart: always
    # networks:
      # - mantis

  phpmyadmin:

    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=root
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions
    depends_on:
      - mysql
    # networks:
      # - mantis

# networks:
  # mantis: