version: '3'

services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mantis
      - MYSQL_USER=mantisbt
      - MYSQL_PASSWORD=mantisbt
    restart: always
    volumes: 
      - ./mysql_dump:/root/mantisbt
      # - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=root
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions
    depends_on:
      - mysql

  mantisbt:
    image: vimagick/mantisbt:latest
    container_name: mantisbt
    restart: always
    ports:
      - "8989:80"
    depends_on:
      - mysql
  
